/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software Server API
 * This is v3 of Schulcloud-Verbund-Software Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { OAuthTokenDto } from '../models';
/**
 * SSOApi - axios parameter creator
 * @export
 */
export const SSOApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} oauthClientId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        oauthSSOControllerGetHydraOauthToken: async (oauthClientId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'oauthClientId' is not null or undefined
            assertParamExists('oauthSSOControllerGetHydraOauthToken', 'oauthClientId', oauthClientId)
            const localVarPath = `/sso/hydra/{oauthClientId}`
                .replace(`{${"oauthClientId"}}`, encodeURIComponent(String(oauthClientId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} oauthClientId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        oauthSSOControllerRequestAuthToken: async (oauthClientId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'oauthClientId' is not null or undefined
            assertParamExists('oauthSSOControllerRequestAuthToken', 'oauthClientId', oauthClientId)
            const localVarPath = `/sso/auth/{oauthClientId}`
                .replace(`{${"oauthClientId"}}`, encodeURIComponent(String(oauthClientId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SSOApi - functional programming interface
 * @export
 */
export const SSOApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SSOApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} oauthClientId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async oauthSSOControllerGetHydraOauthToken(oauthClientId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OAuthTokenDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.oauthSSOControllerGetHydraOauthToken(oauthClientId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} oauthClientId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async oauthSSOControllerRequestAuthToken(oauthClientId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.oauthSSOControllerRequestAuthToken(oauthClientId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SSOApi - factory interface
 * @export
 */
export const SSOApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SSOApiFp(configuration)
    return {
        /**
         * 
         * @param {string} oauthClientId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        oauthSSOControllerGetHydraOauthToken(oauthClientId: string, options?: any): AxiosPromise<OAuthTokenDto> {
            return localVarFp.oauthSSOControllerGetHydraOauthToken(oauthClientId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} oauthClientId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        oauthSSOControllerRequestAuthToken(oauthClientId: string, options?: any): AxiosPromise<object> {
            return localVarFp.oauthSSOControllerRequestAuthToken(oauthClientId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SSOApi - interface
 * @export
 * @interface SSOApi
 */
export interface SSOApiInterface {
    /**
     * 
     * @param {string} oauthClientId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SSOApiInterface
     */
    oauthSSOControllerGetHydraOauthToken(oauthClientId: string, options?: any): AxiosPromise<OAuthTokenDto>;

    /**
     * 
     * @param {string} oauthClientId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SSOApiInterface
     */
    oauthSSOControllerRequestAuthToken(oauthClientId: string, options?: any): AxiosPromise<object>;

}

/**
 * SSOApi - object-oriented interface
 * @export
 * @class SSOApi
 * @extends {BaseAPI}
 */
export class SSOApi extends BaseAPI implements SSOApiInterface {
    /**
     * 
     * @param {string} oauthClientId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SSOApi
     */
    public oauthSSOControllerGetHydraOauthToken(oauthClientId: string, options?: any) {
        return SSOApiFp(this.configuration).oauthSSOControllerGetHydraOauthToken(oauthClientId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} oauthClientId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SSOApi
     */
    public oauthSSOControllerRequestAuthToken(oauthClientId: string, options?: any) {
        return SSOApiFp(this.configuration).oauthSSOControllerRequestAuthToken(oauthClientId, options).then((request) => request(this.axios, this.basePath));
    }
}
