- name: Service
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: "{{ NAMESPACE }}"
    template: svc.yml.j2
    state: "{{ 'present' if WITH_SHD_CLIENT else 'absent'}}"
  tags:
    - service

- name: Configmap
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: "{{ NAMESPACE }}"
    template: configmap.yml.j2
    apply: yes
    state: "{{ 'present' if WITH_SHD_CLIENT else 'absent'}}"
  tags:
    - configmap

- name: Deployment
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: "{{ NAMESPACE }}"
    template: deployment.yml.j2
    state: "{{ 'present' if WITH_SHD_CLIENT else 'absent'}}"
  tags:
    - deployment

- name: Ingress
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: "{{ NAMESPACE }}"
    template: ingress.yml.j2
    state: "{{ 'present' if WITH_SHD_CLIENT else 'absent'}}"
  tags:
    - ingress
