- name: Service
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: "{{ NAMESPACE }}"
    template: svc.yml.j2
    state: absent
  when: WITH_SHD_CLIENT is not defined or not WITH_SHD_CLIENT | bool
  tags:
    - service

- name: Configmap
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: "{{ NAMESPACE }}"
    template: configmap.yml.j2
    apply: yes
    state: absent
  when: WITH_SHD_CLIENT is not defined or not WITH_SHD_CLIENT | bool
  tags:
    - configmap

- name: Deployment
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: "{{ NAMESPACE }}"
    template: deployment.yml.j2
    state: absent
  when: WITH_SHD_CLIENT is not defined or not WITH_SHD_CLIENT | bool
  tags:
    - deployment

- name: Ingress
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: "{{ NAMESPACE }}"
    template: ingress.yml.j2
    state: absent
  when: WITH_SHD_CLIENT is not defined or not WITH_SHD_CLIENT | bool
  tags:
    - ingress
