/* tslint:disable */
/* eslint-disable */
/**
 * Schulcloud-Verbund-Software Server API
 * This is v3 of Schulcloud-Verbund-Software Server. Checkout /docs for v1.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/account-api';
export * from './api/admin-students-api';
export * from './api/admin-teachers-api';
export * from './api/alert-api';
export * from './api/authentication-api';
export * from './api/authorization-api';
export * from './api/board-api';
export * from './api/board-card-api';
export * from './api/board-column-api';
export * from './api/board-element-api';
export * from './api/board-submission-api';
export * from './api/collaborative-storage-api';
export * from './api/collaborative-text-editor-api';
export * from './api/courses-api';
export * from './api/dashboard-api';
export * from './api/default-api';
export * from './api/group-api';
export * from './api/lesson-api';
export * from './api/me-api';
export * from './api/media-board-api';
export * from './api/media-element-api';
export * from './api/media-line-api';
export * from './api/meta-tag-extractor-api';
export * from './api/news-api';
export * from './api/oauth2-api';
export * from './api/pseudonym-api';
export * from './api/rooms-api';
export * from './api/ssoapi';
export * from './api/school-api';
export * from './api/share-token-api';
export * from './api/submission-api';
export * from './api/systems-api';
export * from './api/task-api';
export * from './api/tool-api';
export * from './api/user-api';
export * from './api/user-import-api';
export * from './api/user-login-migration-api';
export * from './api/user-login-migration-rollback-api';
export * from './api/video-conference-api';

